### DISCUSSION TITLE
Discussing building Valhalla on ARM (relates to issues build running it on M1 and M2 macs)

### DISCUSSION THREAD

**Discussion by markstos** [gis-ops/docker-valhalla#127] [Ideas]
I'm wondering if there any known issues with building Valhalla on Arm.  

The issues I found seemed to be around running the x86 build on Arm Macs. 

I'm considering running Valhalla on Arm servers in production due to lower hosting costs. It seems it might be possible with some small changes to the Github Actions workflow file to build a second image:

First, do a marix build with the extra platform:

```
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]
```

Later, Also use the matrix feature for the push step:

```
-  name: Build and push image
        uses: docker/build-push-action@v4
        with:
          platforms: ${{ matrix.platform }}
          tags: my-image:${{ matrix.platform }}
```

Are there extra complications that I'm missing?
