### DISCUSSION TITLE
How to setup and run Valhalla with docker (Windows 10 Pro)

### DISCUSSION THREAD

**Discussion by manKraut** [gis-ops/docker-valhalla#78] [General]
Hi there and thank you for the magical effort to provide such a potential to the open source world of geodata,

I'm trying to pull and build the latest image of Valhalla project from docker and then try to run it, but unfortunately the build process stacks on tiles. My purpose is to use the service that solves the Travel Salesman Problem, by providing geospatial values (lat, lon) and find the best route. Here's what I have done so far:

1) I am on Windows 10 Pro, I have setup correctly (tested) the latest version of docker and I created the following "docker-compose.yml" file:

```
version: '3.0'
services:
  valhalla:
    image: gisops/valhalla:latest
    container_name: valhalla_latest
    ports:
      - 8002:8002
#    restart: always
    #build:
    #  context: .
    #  args:
    #    - VALHALLA_UID=1000
    #    - VALHALLA_GID=1000
    volumes:
      - ./custom_files/:/custom_files
    environment:
      # Auto-download PBFs from Geofabrik
      - tile_urls=https://download.geofabrik.de/europe/greece-latest.osm.pbf
      - server_threads=2  # determines how many threads will be used to run the valhalla server
      - serve_tiles=True  # If True, starts the service. If false, stops after building the graph.
      - use_tiles_ignore_pbf=True  # load existing valhalla_tiles.tar directly
      - tileset_name=valhalla_tiles  # name of the resulting graph on disk
      - build_elevation=False  # build elevation with "True" or "Force": will download only the elevation for areas covered by the graph tiles
      - build_admins=False  # build admins db with "True" or "Force"
      - build_time_zones=False  # build timezone db with "True" or "Force"
      - build_tar=True  # build an indexed tar file from the tile_dir for faster graph loading times
      - force_rebuild=False  # forces a rebuild of the routing tiles with "True"
      # - path_extension=graphs  # this path will be internally appended to /custom_files; no leading or trailing path separator!
    # adapt to the expected build time
    # healthcheck:
    #   test: curl --fail -s http://localhost:8002/status || exit 1
    #   interval: 1s
    #   retries: 10
    #   start_period: 2s
    #   timeout: 1s
```

2) I run the command `docker compose up --build` 

The process runs well until some warnings start to appear (" Admin db /custom_files/admin_data/admins.sqlite not found", "Time zone db /custom_files/timezone_data/timezones.sqlite not found", "Exceeding maximum.  Average speed: 150", " Local index 12 exceeds max value of 7, returning heading of 0") and then, after a while it stacks during warnings about traffic tiles (see pic below):

![sss](https://user-images.githubusercontent.com/34462260/203261773-209968e7-6f48-40c4-99b3-c52eeee5eb5a.PNG)

Some notes for the above:

a) The yml file I found indicates version: '3.0'. I found in another [discussion](https://github.com/valhalla/valhalla/discussions/3410) uses of '3.3' or '3.9', so I am not sure where it refers to.
b) You will note that some lines in yml file are commented out
c) The region is Greece
d) I 've left it running all night long but it didn't go through. The CPU and memory were running in normal levels.
e) I use Pycharm IDE and I work inside a virtual environment (venv)

Any suggestions about the above would be helpful. Thank you in advance!
