### ISSUE TITLE
Including construction roads

### ISSUE THREAD

**Issue by aez99** [gis-ops/docker-valhalla#109]
Hello,

Here is my `docker-compose.yml`

```yaml
version: '3.0'
services:
  valhalla:
    image: gisops/valhalla:latest
    ports:
      - "8002:8002"
    volumes:
      - ./custom_files/:/custom_files
    environment:.
      - tile_urls=https://download.geofabrik.de/europe/turkey-latest.osm.pbf
      # Get correct bounding box from e.g. https://boundingbox.klokantech.com/
      - min_x=26 
      - min_y=36 
      - max_x=44 
      - max_y=41 
      - use_tiles_ignore_pbf=False #True
      - force_rebuild=True #False
      - force_rebuild_elevation=True #False
      - build_elevation=True
      - build_admins=True
      - build_time_zones=True
```

In order to include roads under construction in route planning I set include_construction to true in valhalla.json. Then I tried restarting the container, re-building (docker-compose up --build), and changing use_tiles_ignore_pbf/force_rebuild/force_rebuild_elevation to the commented out values then re-building but Valhalla still couldn't manage to set a route through the road under construction after any of these changes. Any ideas? Thanks in advance!
