### ISSUE TITLE
Cannot download elevation tiles

### ISSUE THREAD

**Issue by JackCaster** [gis-ops/docker-valhalla#42]
I am using the latest docker image. I created a docker-compose file like
```yaml
version: "3.0"
services:
  valhalla:
    image: gisops/valhalla:latest
    restart: "no" # or on_failure
    ports:
      - "8002:8002"
    volumes:
      - ./custom_files:/valhalla_files # be sure this folder does _not_ already exist in the host. Docker will create at runtime the folder in the host and it will populate it with the files in the container.
    environment:
      # The tile_file must be located in the `custom_files` folder.
      # The tile_file has priority and is used when valid.
      # If the tile_file doesn't exist, the url is used instead.
      # Don't blank out tile_url when you use tile_file and vice versa.
      - tile_urls=https://download.geofabrik.de/europe/malta-latest.osm.pbf
      - use_tiles_ignore_pbf=False
      - force_rebuild=True
      - force_rebuild_elevation=True
      - build_elevation=True
      - build_admins=True
      - build_time_zones=True
```

 but I got
```
valhalla-local-valhalla-1  | =================================
valhalla-local-valhalla-1  | = Download the elevation tiles =
valhalla-local-valhalla-1  | =================================
valhalla-local-valhalla-1  | Traceback (most recent call last):
valhalla-local-valhalla-1  |   File "/usr/lib/python3.8/pathlib.py", line 1288, in mkdir
valhalla-local-valhalla-1  |     self._accessor.mkdir(self, mode)
valhalla-local-valhalla-1  | FileNotFoundError: [Errno 2] No such file or directory: '/data/valhalla/elevation/N36'
valhalla-local-valhalla-1  |
valhalla-local-valhalla-1  | During handling of the above exception, another exception occurred:
valhalla-local-valhalla-1  |
valhalla-local-valhalla-1  | Traceback (most recent call last):
valhalla-local-valhalla-1  |   File "/usr/lib/python3.8/pathlib.py", line 1288, in mkdir
valhalla-local-valhalla-1  |     self._accessor.mkdir(self, mode)
valhalla-local-valhalla-1  | FileNotFoundError: [Errno 2] No such file or directory: '/data/valhalla/elevation'
valhalla-local-valhalla-1  |
valhalla-local-valhalla-1  | During handling of the above exception, another exception occurred:
valhalla-local-valhalla-1  |
valhalla-local-valhalla-1  | Traceback (most recent call last):
valhalla-local-valhalla-1  |   File "/usr/lib/python3.8/pathlib.py", line 1288, in mkdir
valhalla-local-valhalla-1  |     self._accessor.mkdir(self, mode)
valhalla-local-valhalla-1  | FileNotFoundError: [Errno 2] No such file or directory: '/data/valhalla'
valhalla-local-valhalla-1  |
valhalla-local-valhalla-1  | During handling of the above exception, another exception occurred:
valhalla-local-valhalla-1  |
valhalla-local-valhalla-1  | Traceback (most recent call last):
valhalla-local-valhalla-1  |   File "/usr/local/bin/valhalla_build_elevation", line 248, in <module>
valhalla-local-valhalla-1  |     sum_downloaded = list(filter(lambda res: res is True, results))
valhalla-local-valhalla-1  |   File "/usr/lib/python3.8/multiprocessing/pool.py", line 868, in next
valhalla-local-valhalla-1  |     raise value
valhalla-local-valhalla-1  |   File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
valhalla-local-valhalla-1  |     result = (True, func(*args, **kwds))
valhalla-local-valhalla-1  |   File "/usr/local/bin/valhalla_build_elevation", line 190, in download
valhalla-local-valhalla-1  |     dest_directory.mkdir(parents=True, exist_ok=True)
valhalla-local-valhalla-1  |   File "/usr/lib/python3.8/pathlib.py", line 1292, in mkdir
valhalla-local-valhalla-1  |     self.parent.mkdir(parents=True, exist_ok=True)
valhalla-local-valhalla-1  |   File "/usr/lib/python3.8/pathlib.py", line 1292, in mkdir
valhalla-local-valhalla-1  |     self.parent.mkdir(parents=True, exist_ok=True)
valhalla-local-valhalla-1  |   File "/usr/lib/python3.8/pathlib.py", line 1292, in mkdir
valhalla-local-valhalla-1  |     self.parent.mkdir(parents=True, exist_ok=True)
valhalla-local-valhalla-1  |   File "/usr/lib/python3.8/pathlib.py", line 1288, in mkdir
valhalla-local-valhalla-1  |     self._accessor.mkdir(self, mode)
valhalla-local-valhalla-1  | PermissionError: [Errno 13] Permission denied: '/data'
valhalla-local-valhalla-1 exited with code 1
```

Is this something you could help me with?
