### ISSUE TITLE
Crash in configure_valhalla.sh

### ISSUE THREAD

**Issue by flodaniel** [gis-ops/docker-valhalla#46]
I pulled your image today and use the template docker-compose.yml. However I get the following error:

![image](https://user-images.githubusercontent.com/6661557/146008288-a0e77eae-0030-4b9f-a7db-2312d8126ad2.png)

It seems to wrongly build the path, as the pbf file is not located in `custom_files/graphs` but directly in `custom_files`.

This is my docker-compose.yml

```
version: "3.0"
services:
  valhalla:
    image: gisops/valhalla:latest
    container_name: valhalla_latest
    ports:
      - 8002:8002
    #build:
    #  context: .
    #  args:
    #    - VALHALLA_UID=1000
    #    - VALHALLA_GID=1000
    volumes:
      - ./custom_files:/custom_files
    environment:
      # Auto-download PBFs from Geofabrik
      # - "tile_urls=https://download.geofabrik.de/north-america/us/california-latest.osm.pbf https://download.geofabrik.de/europe/austria-latest.osm.pbf"
      - tile_urls=https://download.geofabrik.de/europe/austria-latest.osm.pbf
      - server_threads=2 # determines how many threads will be used to run the valhalla server
      - use_tiles_ignore_pbf=True # load existing valhalla_tiles.tar directly
      - build_elevation=False # build elevation with "True" or "Force": will download only the elevation for areas covered by the graph tiles
      - build_admins=False # build admins db with "True" or "Force"
      - build_time_zones=False # build timezone db with "True" or "Force"
      - build_tar=True # build an indexed tar file from the tile_dir for faster graph loading times
      - force_rebuild=False # forces a rebuild of the routing tiles with "True"
      - path_extension=graphs # this path will be internally appended to /custom_files; no leading or trailing path separator!

```
