### ISSUE TITLE
Silent crash in the valhalla_build_tiles -c. valhalla_tiles.tar generated empty. 

### ISSUE THREAD

**Issue by waldobeest** [gis-ops/docker-valhalla#6]
Docker-Compose File:

```
  valhalla:
    image: gisops/valhalla:latest
    ports:
      - "8002:8002"
    volumes:
      - ./volumes/valhalla/custom_files/:/custom_files
    environment:
      - tile_urls=https://download.geofabrik.de/africa/south-africa-latest.osm.pbf
      - use_tiles_ignore_pbf=False
      - force_rebuild=False
      - force_rebuild_elevation=False
      - build_elevation=False
      - build_admins=False
      - build_time_zones=False
```

Docker Logs:

```
valhalla_1  | Running build tiles with: /custom_files/valhalla.json  /custom_files/south-africa-latest.osm.pbf
valhalla_1  | 2020/08/06 08:27:52.423473 [INFO] Start stage = initialize End stage = cleanup
valhalla_1  | 2020/08/06 08:27:52.837064 [INFO] Parsing files: /custom_files/south-africa-latest.osm.pbf
valhalla_1  | 2020/08/06 08:27:52.837886 [INFO] Parsing ways...
valhalla_1  | 2020/08/06 08:27:55.739320 [WARN] Max osmid exceeded bitset, resizing to fit id: 7511663645
valhalla_1  | 2020/08/06 08:28:00.342288 [WARN] Max osmid exceeded bitset, resizing to fit id: 7605502764
valhalla_1  | 2020/08/06 08:28:00.349899 [WARN] Max osmid exceeded bitset, resizing to fit id: 7193094398
valhalla_1  | /valhalla/scripts/configure_valhalla.sh: line 291:    14 Killed                  valhalla_build_tiles -c ${config_file} ${files}
valhalla_1  | Successfully build files:  /custom_files/south-africa-latest.osm.pbf
valhalla_1  | Hashing files:  /custom_files/south-africa-latest.osm.pbf /custom_files/valhalla_tiles.tar
valhalla_1  | Hashing file: /custom_files/south-africa-latest.osm.pbf
valhalla_1  | Hashing file: /custom_files/valhalla_tiles.tar
valhalla_1  | Found config file. Starting valhalla service!
valhalla_1  | 2020/08/06 08:28:04.328340 [WARN] Tile extract contained no usuable tiles
valhalla_1  | 2020/08/06 08:28:04.340128 [WARN] /data/valhalla/elevation/ currently has no elevation tiles
```

This then results in a Postman request to:
`http://localhost:8002/route?json={"verbose":true,"locations":[{"lat":-25.7482297,"lon":28.2337938},{"lat":-26.271064,"lon":27.979535}],"costing":"auto"}`

Resulting in:

```
{
    "error_code": 171,
    "error": "No suitable edges near location",
    "status_code": 400,
    "status": "Bad Request"
}

```
