### ISSUE TITLE
Memory usage increases linearly with server_threads

### ISSUE THREAD

**Issue by ktnr** [gis-ops/docker-valhalla#81]
Follow up on #58 and #63. With `server_threads=1`, memory usage increases to 4GB on the first call and does not increase on subsequent calls (with exactly the same matrix request). Everything is fine. With `server_threads=2`, memory usage increases to 4GB on the first call and 8GB on the second call, but does not increase on the third call.

At first I had `server_threads` unset because I followed [this tutorial](https://gis-ops.com/valhalla-how-to-run-with-docker-on-ubuntu/), so it defaulted to `nproc`. This explains the increase in memory usage atleast in my case, as explained in https://github.com/gis-ops/docker-valhalla/issues/58#issuecomment-1342910517. 

Is this expected behavior? The data is only accessed by read operations, right?

**Comment by kevinkreiser** [comment]
When using memory mapping each thread gets access to the map which will reported as the amount the os has ram cached multiplied by the number of open handles to the map. In this way memory usage can actually report above 100 percent iirc. Matrix though had some interesting dynamically allocated memory requirements which we may have neglected to trim back after each request. Do you get this or a similar behavior with route requests?

**Comment by nilsnolde** [comment]
Well, the funny thing is it happens only with our image, not with the Valhalla native one. With the same graph and the same requests. Don't understand.. Or know how to approach that..

**Comment by ktnr** [comment]
@nilsnolde: Cannot yet confirm that it's exactly the same behavior for the native valhalla image as I'm not sure I set/it defaulted to the same `server_thread` count.

Will also test the behavior for route requests.

**Comment by ktnr** [comment]
Alright. Same memory usage behavior for the matrix and route endpoint when using `gis-ops/valhalla` and `valhalla/valhalla` with the same `server_threads`, even when executing the same exact request multiple times: linear increase with `server_threads` and capped by `max ram usage * server_threads`.

For completeness, I'll attach the matrix request and valhalla config: [valhalla-memory_increase.zip](https://github.com/gis-ops/docker-valhalla/files/10193038/valhalla-memory_increase.zip). Here's the route request
```
curl http://localhost:8002/route --data '{"locations":[{"lat":47.619904,"lon":12.902326},{"lat":51.717959,"lon":6.217763}],"costing":"auto"}'
```
and the compose file:
```
version: '3.0'
services:
  valhalla:
    image: gisops/valhalla:latest
    ports:
      - "8002:8002"
    volumes:
      - ${HOME}/downloads/map-data/valhalla/custom_files:/custom_files
    #mem_limit: 10g
    #cpus: 1
    environment:
      # The tile_file must be located in the `custom_files` folder.
      # The tile_file has priority and is used when valid.
      # If the tile_file doesn't exist, the url is used instead.
      # Don't blank out tile_url when you use tile_file and vice versa.
      - tile_urls=europe/germany-latest.osm.pbf
      - use_tiles_ignore_pbf=True
      - force_rebuild=False
      - force_rebuild_elevation=False
      - build_elevation=False
      - build_admins=True
      - build_time_zones=True
      - server_threads=2  # determines how many threads will be used to run the valhalla server
      
  valhalla-native:
    image: valhalla/valhalla:run-latest
    command:
      - /bin/bash
      - -c
      - |
        valhalla_service custom_files/valhalla.json 2
    ports:
      - 8002:8002
    volumes:
      - ${HOME}/downloads/map-data/valhalla/custom_files:/custom_files
    #mem_limit: 10g
    #cpus: 1
```

From what @kevinkreiser said above and in https://github.com/valhalla/valhalla/discussions/3405#discussioncomment-1645327, I wouldn't expect the increase in memory.
