### ISSUE TITLE
Empty polygon in avoid_polygons causes container to crash

### ISSUE THREAD

**Issue by isakengstrom** [gis-ops/docker-valhalla#82]
Hi,

I ran into a bug with the avoid_polygons/exclude_polygons which causes the container to stop. If I send in an empty polygon array to the avoid_polygons array, it causes a **segmentation fault**:

 
![Screenshot 2023-01-12 110348](https://user-images.githubusercontent.com/47446279/212037557-e257e463-4b02-4854-9928-2ca6b267fb7c.png)

Issue occurs when running the following get request:

localhost:8002/route?json={"locations":[{"lat":58.403618,"lon":15.556376},{"lat":58.406674,"lon":15.559801}],"costing":"bus","directionType":"none","avoid_polygons":[[]]}

Beautified json of the request:
```json
{
    "locations": [
        {
            "lat": 58.403618,
            "lon": 15.556376
        },
        {
            "lat": 58.406674,
            "lon": 15.559801
        }
    ],
    "costing": "bus",
    "directionType": "none",
    "avoid_polygons": [
        [
           
        ]
    ]
}
```

---

**Expexted behaviour**
To get a response similar to:
```json
{
    "error_code": 137,
    "error": "Failed to parse polygon",
    "status_code": 400,
    "status": "Bad Request"
} 
```
**Actual behaviour**
Container crashes and requires a restart

---
Setup:
- Latest Valhalla Image
- Latest pbf file of sweden from Geofabrik

I'm using the following docker-compose YAML config to start the container:
```yaml
version: '3.8'
services:
    valhalla:
        image: gisops/valhalla:latest
        container_name: valhalla_latest
        ports:
            - '8002:8002'
        environment:
            - tile_urls=http://download.geofabrik.de/europe/sweden-latest.osm.pbf
            - build_elevation=False 
            - build_admins=False 
            - build_time_zones=False 
            - force_rebuild=False
```
